#include <iostream>
#include <fstream>
#include <string>

#define TAB "    "

int main(int argc, char** argv)
{
    if (argc < 2)
    {
        std::cout << "Not enough arg" << std::endl;
        exit(1);
    }

    std::string class_name = argv[1];
    std::string header_file_name(class_name + ".gen.hpp");
    std::string cpp_file_name(class_name + ".gen.cpp");

    std::ofstream header_file(header_file_name);
    std::ofstream cpp_file(cpp_file_name);

    header_file
        << "/********************************************\n"
        << " ** This file is generated by AppGenerator **\n"
        << " ********************************************/\n"
        << "\n"
        << "#pragma once\n"
        << "#include \"cedec2022_demo.hpp\"\n"
        << "#include \"send_osc.h\"\n"
        << "#include \"demo_app_base.hpp\"\n"
        << "\n"
        << "#include \"TLL.h\"\n"
        << "\n"
        << "#include <TuioListener.h>\n"
        << "#include <UdpReceiver.h>\n"
        << "#include <TuioClient.h>\n"
        << "\n"
        << "#include \"osc/OscReceivedElements.h\"\n"
        << "#include \"osc/OscPacketListener.h\"\n"
        << "#include \"osc/OscOutboundPacketStream.h\"\n"
        << "#include \"ip/UdpSocket.h\"\n"
        << "#include \"ip/IpEndpointName.h\"\n"
        << "\n"
        << "using namespace tll;\n"
        << "using namespace TUIO;\n"
        << "\n"
        << "class " << class_name << ": public AppBase\n"
        << "{\n"
        << "public:\n"
        << TAB << class_name << "() {}\n"
        << TAB << "~" << class_name << "() {}\n"
        << "\n"
        << TAB << "static " << class_name << "* load();\n"
        << "\n"
        << TAB << "void init() override;\n"
        << TAB << "void run() override;\n"
        << TAB << "void terminate() override;\n"
        << TAB << "void procMessage(const char* msg) override;\n"
        << "\n"
        << TAB << "void onTouched() override;\n"
        << TAB << "void onMoved() override;\n"
        << TAB << "void onReleased() override;\n"
        << "};\n";

    cpp_file
        << "/********************************************\n"
        << " ** This file is generated by AppGenerator **\n"
        << " ********************************************/\n"
        << "\n"
        << "#include \"" << header_file_name << "\"\n"
        << "\n"
        << class_name << "* " << class_name << "::load()\n"
        << "{\n"
        << TAB << "return AppBase::load<" << class_name << ">();\n"
        << "}\n"
        << "\n"
        << "void " << class_name << "::init()\n"
        << "{\n"
        << "\n"
        << "}\n"
        << "\n"
        << "void " << class_name << "::run()\n"
        << "{\n"
        << "\n"
        << "}\n"
        << "\n"
        << "void " << class_name << "::terminate()\n"
        << "{\n"
        << "\n"
        << "}\n"
        << "\n"
        << "void " << class_name << "::procMessage(const char* msg)\n"
        << "{\n"
        << "\n"
        << "}\n"
        << "\n"
        << "void " << class_name << "::onTouched()\n"
        << "\n"
        << "}\n"
        << "\n"
        << "void " << class_name << "::onMoved())\n"
        << "\n"
        << "}\n"
        << "\n"
        << "void " << class_name << "::onReleased()\n"
        << "\n"
        << "}\n";

    header_file.close();
    cpp_file.close();

    std::cout << "Create <" << header_file_name << ">, <" << cpp_file_name << ">" << std::endl;
}
