/********************************************
 ** This file is generated by AppGenerator **
 ********************************************/

#include "VoiceRecognition.gen.hpp"

VoiceRecognition* VoiceRecognition::load()
{
    return AppBase::load<VoiceRecognition>();
}

void VoiceRecognition::init()
{
    sendOscMessage("/tll/app/voice/init");
    std::cout << "Start up \"VoiceRecognition\"" << std::endl;
}

void VoiceRecognition::run()
{
    this->is_running = true;

    while (loop())
    {
        if (!this->is_running)
            break;
    }
}

void VoiceRecognition::terminate()
{
    sendOscMessage("/tll/app/voice/terminate");
    std::cout << "Terminate \"VoiceRecognition\"" << std::endl;
}

void VoiceRecognition::procMessage(const osc::ReceivedMessage& msg)
{
    if (strcmp(msg.AddressPattern(), "/tll/app/voice/bomb_notify") == 0)
    {
        Video video = loadVideo("bomb.mp4");
        video.play(0, 0, 22);
    }
}

void VoiceRecognition::onTouched(uint32_t x, uint32_t y)
{

}

void VoiceRecognition::onMoved(uint32_t x, uint32_t y)
{

}

void VoiceRecognition::onReleased()
{

}
