/********************************************
 ** This file is generated by AppGenerator **
 ********************************************/

#include "ADIR01P_Light.gen.hpp"
#include "TLL.h"

#include <iostream>

ADIR01P_Light::ADIR01P_Light()
    : pressed_(false)
    , light_on_(false)
{
    std::cout << "Create ADIR01P_Light instance." << std::endl;
}

ADIR01P_Light::~ADIR01P_Light()
{
    std::cout << "Delete ADIR01P_Light instance." << std::endl;
}

void ADIR01P_Light::init()
{

}

void ADIR01P_Light::run()
{
    tll::clear();

    if (!this->pressed_)
    {
        tll::drawRect(24, 8, 16, 16, tll::Color(255, 255, 255));
    }
    else
    {
        tll::drawRect(24, 8, 16, 16, tll::Color(128, 128, 128));
    }

    if (this->light_on_)
    {
        tll::drawRect(10, 0, 44, 3, tll::Color(200, 200, 0));
    }
}

void ADIR01P_Light::terminate()
{

}

void ADIR01P_Light::onTouched(tll::TouchInfo ti)
{
    if (ti.id != 0)
        return;

    this->pressed_ = (24 <= ti.x && ti.x <= 40 && 8 <= ti.y && ti.y <= 24);
}

void ADIR01P_Light::onMoved(tll::TouchInfo ti)
{
    if (ti.id != 0)
        return;

    this->pressed_ = (24 <= ti.x && ti.x <= 40 && 8 <= ti.y && ti.y <= 24);
}

void ADIR01P_Light::onReleased(tll::TouchInfo ti)
{
    if (ti.id != 0)
        return;

    if (this->pressed_)
    {
        if (this->light_on_)
        {
            tll::OscHandler::sendMessage("/tll/app/light/off", "192.168.0.101", 3333);
            this->light_on_ = false;
        }
        else
        {
            tll::OscHandler::sendMessage("/tll/app/light/on", "192.168.0.101", 3333);
            this->light_on_ = true;
        }

        this->pressed_ = false;
    }
}
