/********************************************
 ** This file is generated by AppGenerator **
 ********************************************/

#pragma once

#include "AppInterface.hpp"
#include "TLL.h"

#include <cstdint>
#include <memory>

class Cockroach
{
public:
    Cockroach(uint16_t x, uint16_t y, uint16_t vx, uint16_t vy);

    void move();
    void draw();

    uint16_t x, vx;
    uint16_t y, vy;
};

class CockroachShooting : public tll::AppInterface
{
public:
    CockroachShooting();
    ~CockroachShooting();

    void init() override;
    void run() override;
    void terminate() override;

    void onTouched(tll::TouchInfo ti) override;
    void onMoved(tll::TouchInfo ti) override;
    void onReleased(tll::TouchInfo ti) override;

    Cockroach* cockroach;
};

/* Required to use in loading application file */
extern "C"
{
    std::unique_ptr<tll::AppInterface> create()
    {
        return std::unique_ptr<tll::AppInterface>(new CockroachShooting);
    }
}
