/********************************************
 ** This file is generated by AppGenerator **
 ********************************************/

#pragma once

#include "AppInterface.hpp"
#include "TLL.h"

#include <cstdint>
#include <memory>

enum GameState
{
    TITLE,
    IN_GAME,
    FINISHED,
};

class Cockroach
{
public:
    Cockroach(uint16_t x, uint16_t y, uint16_t vx, uint16_t vy);

    void move();
    void draw();

    uint16_t x, vx;
    uint16_t y, vy;
};

class CockroachShooting : public tll::AppInterface
{
public:
    CockroachShooting();
    ~CockroachShooting();

    void init() override;
    void run() override;
    void terminate() override;

    void onTouched(tll::TouchInfo ti) override;
    void onMoved(tll::TouchInfo ti) override;
    void onReleased(tll::TouchInfo ti) override;

    void drawReticle(uint32_t x1, uint32_t y1, uint32_t x2, uint32_t y2, uint32_t x3, uint32_t y3);

    std::vector<Cockroach*> cockroach;

    tll::TouchInfo points[3];

    /* Game state variables */
    GameState game_state;
    int32_t level;

    /* Button components */
    tll::Image* button_start;
};

/* Required to use in loading application file */
extern "C"
{
    std::unique_ptr<tll::AppInterface> create()
    {
        return std::unique_ptr<tll::AppInterface>(new CockroachShooting);
    }
}
