/********************************************
 ** This file is generated by AppGenerator **
 ********************************************/

#include "ImageViewer.gen.hpp"
#include "TLL.h"

#include <iostream>

ImageViewer::ImageViewer()
{
    std::cout << "Create ImageViewer instance." << std::endl;
}

ImageViewer::~ImageViewer()
{
    std::cout << "Delete ImageViewer instance." << std::endl;
}

void ImageViewer::init()
{
    this->image_list.push_back(tll::loadImage("image/WISS_Logo.png"));
    this->image_list.push_back(tll::loadImage("image/Icon.png"));

    for (int i = 0; i < this->image_list.size(); i++)
    {
        this->image_list[i]->resize(32, 64);
    }
}

void ImageViewer::run()
{
    this->image_list[this->img_index]->draw(0, 0);
}

void ImageViewer::terminate()
{

}

void ImageViewer::onTouched(tll::TouchInfo ti)
{
    this->img_index = (this->img_index + 1) % this->image_list.size();
}

void ImageViewer::onMoved(tll::TouchInfo ti)
{

}

void ImageViewer::onReleased(tll::TouchInfo ti)
{

}
