/********************************************
 ** This file is generated by AppGenerator **
 ********************************************/

#pragma once

#include "AppInterface.hpp"
#include "TLL.h"

#include <cstdint>
#include <memory>
#include <vector>

class ImageViewer : public tll::AppInterface
{
public:
    ImageViewer();
    ~ImageViewer();

    void init() override;
    void run() override;
    void terminate() override;

    void onTouched(tll::TouchInfo ti) override;
    void onMoved(tll::TouchInfo ti) override;
    void onReleased(tll::TouchInfo ti) override;

private:
    std::vector<tll::Image*> image_list;

    uint32_t img_index = 0;
};

/* Required to use in loading application file */
extern "C"
{
    std::unique_ptr<tll::AppInterface> create()
    {
        return std::unique_ptr<tll::AppInterface>(new ImageViewer);
    }
}
