/********************************************
 ** This file is generated by AppGenerator **
 ********************************************/

#include "MarbleTower.gen.hpp"
#include "TLL.h"

#include <iostream>
#include <cmath>

#define DEST_IP "192.168.1.6"
#define DEST_PORT 33331

#define STROKE_THRESHOLD 3

using std::sqrt;
using std::pow;

MarbleTower::MarbleTower()
{
    std::cout << "Create MarbleTower instance." << std::endl;
}

MarbleTower::~MarbleTower()
{
    std::cout << "Delete MarbleTower instance." << std::endl;
}

void MarbleTower::init()
{

}

void MarbleTower::run()
{

}

void MarbleTower::terminate()
{

}

void MarbleTower::onTouched(tll::TouchInfo ti)
{
    if (ti.id != 0)
        return;

    tll::OscHandler::sendMessageWithInt32("/tll/app/tower/stroke/x", ti.x, DEST_IP, DEST_PORT);
    tll::OscHandler::sendMessageWithInt32("/tll/app/tower/stroke/y", ti.y, DEST_IP, DEST_PORT);

    tll::drawRect(ti.x - 1, ti.y - 1, 2, 2, tll::Color(255, 255, 255));

    this->current_x = ti.x;
    this->current_y = ti.y;
}

void MarbleTower::onMoved(tll::TouchInfo ti)
{
    if (ti.id != 0)
        return;

    if (sqrt(pow(ti.x - this->current_x, 2) + pow(ti.y - this->current_y, 2)) < STROKE_THRESHOLD)
        return;

    tll::OscHandler::sendMessageWithInt32("/tll/app/tower/stroke/x", ti.x, DEST_IP, DEST_PORT);
    tll::OscHandler::sendMessageWithInt32("/tll/app/tower/stroke/y", ti.y, DEST_IP, DEST_PORT);

    tll::drawRect(ti.x - 2, ti.y - 2, 4, 4, tll::Color(255, 255, 255));

    this->current_x = ti.x;
    this->current_y = ti.y;
}

void MarbleTower::onReleased(tll::TouchInfo ti)
{
    tll::OscHandler::sendMessage("/tll/app/tower/stroke/end", DEST_IP, DEST_PORT);

    tll::clear();
}
