/********************************************
 ** This file is generated by AppGenerator **
 ********************************************/

#pragma once

#include "AppInterface.hpp"

#include <cstdint>
#include <memory>
#include <utility>

struct Point
{
public:
    int32_t x;
    int32_t y;
    bool touched = false;
};

class MultiTouchLine : public tll::AppInterface
{
public:
    MultiTouchLine();
    ~MultiTouchLine();

    void init() override;
    void run() override;
    void terminate() override;

    void onTouched(tll::TouchInfo ti) override;
    void onMoved(tll::TouchInfo ti) override;
    void onReleased(tll::TouchInfo ti) override;

private:
    void updatePoint(tll::TouchInfo ti, bool touched);

    void connectTwoPoints();
    void disconnectTwoPoints();

    bool multi_touched;
    std::pair<Point, Point> points;
};

/* Required to use in loading application file */
extern "C"
{
    std::unique_ptr<tll::AppInterface> create()
    {
        return std::unique_ptr<tll::AppInterface>(new MultiTouchLine);
    }
}
