/********************************************
 ** This file is generated by AppGenerator **
 ********************************************/

#pragma once

#include "AppInterface.hpp"

#include <chrono>
#include <cstdint>
#include <memory>

class MusicVisualizer : public tll::AppInterface
{
public:
    MusicVisualizer();
    ~MusicVisualizer();

    void init() override;
    void run() override;
    void terminate() override;

    void onTouched(tll::TouchInfo ti) override;
    void onMoved(tll::TouchInfo ti) override;
    void onReleased(tll::TouchInfo ti) override;

    void procOscMessage(const osc::ReceivedMessage& msg) override;

private:
    void beatNotified();

    std::chrono::system_clock::time_point pre_pre_tp;
    std::chrono::system_clock::time_point pre_tp;

    double pre_pre_elapse = 0.0;
    double pre_elapse = 0.0;

    uint16_t x = 32;
    uint16_t y = 16;

    int32_t rad = 0;
};

/* Required to use in loading application file */
extern "C"
{
    std::unique_ptr<tll::AppInterface> create()
    {
        return std::unique_ptr<tll::AppInterface>(new MusicVisualizer);
    }
}
