/********************************************
 ** This file is generated by AppGenerator **
 ********************************************/

#include "OscTestApp.gen.hpp"
#include "TLL.h"

#include <iostream>

OscTestApp::OscTestApp()
{
    std::cout << "Create OscTestApp instance." << std::endl;}

OscTestApp::~OscTestApp()
{
    std::cout << "Delete OscTestApp instance." << std::endl;}

void OscTestApp::init()
{

}

void OscTestApp::run()
{

}

void OscTestApp::terminate()
{

}

void OscTestApp::onTouched(uint32_t x, uint32_t y)
{

}

void OscTestApp::onMoved(uint32_t x, uint32_t y)
{

}

void OscTestApp::onReleased()
{

}

void OscTestApp::procOscMessage(const osc::ReceivedMessage& msg)
{
    
}
