/********************************************
 ** This file is generated by AppGenerator **
 ********************************************/

#include "Pong.gen.hpp"

#include <iostream>

Pong::Pong()
{
    std::cout << "Create Pong instance." << std::endl;
}

Pong::~Pong()
{
    std::cout << "Delete Pong instance." << std::endl;
}

void Pong::init()
{
    this->p1 = new Player(tll::Palette::Red    ,  4, 16);
    this->p2 = new Player(tll::Color(0, 255, 0), 58, 16);
}

void Pong::run()
{
    this->drawBoard();
    this->drawPlayers();
}

void Pong::terminate()
{

}

void Pong::onTouched(tll::TouchInfo ti)
{

}

void Pong::onMoved(tll::TouchInfo ti)
{

}

void Pong::onReleased(tll::TouchInfo ti)
{

}

void Pong::drawBoard()
{
    tll::drawRect (0,  0, 64,  2, tll::Palette::Aqua);
    tll::drawRect( 0,  0,  2, 32, tll::Palette::Aqua);
    tll::drawRect( 0, 30, 64,  2, tll::Palette::Aqua);
    tll::drawRect(62,  0,  2, 32, tll::Palette::Aqua);
}

void Pong::drawPlayers()
{
    tll::drawRect(this->p1->x, this->p1->y - 3, 2, 6, this->p1->color);
    tll::drawRect(this->p2->x, this->p2->y - 3, 2, 6, this->p2->color);
}
