/********************************************
 ** This file is generated by AppGenerator **
 ********************************************/

#include "SimpleScan.gen.hpp"
#include "TLL.h"

#include <chrono>
#include <iostream>
#include <thread>

tll::Color c(255, 0, 0);

SimpleScan::SimpleScan()
{
    std::cout << "Create SimpleScan instance." << std::endl;
}

SimpleScan::~SimpleScan()
{
    std::cout << "Delete SimpleScan instance." << std::endl;
}

void SimpleScan::init()
{

}

void SimpleScan::run()
{
    tll::drawRect(0, 0, 64, 32, c);
    
    if (c.r_ == 255 && c.g_ < 255 && c.b_ == 0)
    {
        c.g_++;
    }
    else if (c.r_ > 0 && c.g_ == 255 && c.b_ == 0)
    {
        c.r_--;
    }
    else if (c.r_ == 0 && c.g_ == 255 && c.b_ < 255)
    {
        c.b_++;
    }
    else if (c.r_ == 0 && c.g_ > 0 && c.b_ == 255)
    {
        c.g_--;
    }
    else if (c.r_ < 255 && c.g_ == 0 && c.b_ == 255)
    {
        c.r_++;
    }
    else if (c.r_ == 255 && c.g_ == 0 && c.b_ > 0)
    {
        c.b_--;
    }
}

void SimpleScan::terminate()
{

}

void SimpleScan::onTouched(tll::TouchInfo ti)
{

}

void SimpleScan::onMoved(tll::TouchInfo ti)
{

}

void SimpleScan::onReleased(tll::TouchInfo ti)
{

}
