/********************************************
 ** This file is generated by AppGenerator **
 ********************************************/

#include "SimpleScan.gen.hpp"
#include "TLL.h"

#include <chrono>
#include <iostream>
#include <thread>

SimpleScan::SimpleScan()
{
    std::cout << "Create SimpleScan instance." << std::endl;
}

SimpleScan::~SimpleScan()
{
    std::cout << "Delete SimpleScan instance." << std::endl;
}

void SimpleScan::init()
{
    this->is_running = true;
}

void SimpleScan::run()
{
    while (tll::loop())
    {
        if (!this->is_running)
            return;

        drawNextPt();
    }
}

void SimpleScan::terminate()
{
    this->is_running = false;
}

void SimpleScan::onTouched(uint32_t x, uint32_t y)
{

}

void SimpleScan::onMoved(uint32_t x, uint32_t y)
{

}

void SimpleScan::onReleased()
{

}

void SimpleScan::drawNextPt()
{
    static int x = 0;
    static int y = 0;

    std::this_thread::sleep_for(std::chrono::milliseconds(16));
    tll::clear();
    tll::drawPixel(x++, y, tll::Palette::White);

    x = x % 64;
    y = y % 32;

    if (x == 0) ++y;
}
