/********************************************
 ** This file is generated by AppGenerator **
 ********************************************/

#include "SimpleScan.gen.hpp"
#include "TLL.h"

#include <chrono>
#include <iostream>
#include <thread>

SimpleScan::SimpleScan()
{
    std::cout << "Create SimpleScan instance." << std::endl;
}

SimpleScan::~SimpleScan()
{
    std::cout << "Delete SimpleScan instance." << std::endl;
}

void SimpleScan::init()
{

}

void SimpleScan::run()
{
    drawNextPt();
}

void SimpleScan::terminate()
{

}

void SimpleScan::onTouched(tll::TouchInfo ti)
{

}

void SimpleScan::onMoved(tll::TouchInfo ti)
{

}

void SimpleScan::onReleased(tll::TouchInfo ti)
{

}

void SimpleScan::drawNextPt()
{
    static int x = 0;
    static int y = 0;

    std::this_thread::sleep_for(std::chrono::milliseconds(16));
    tll::clear();
    tll::drawPixel(x++, y, tll::Palette::White);

    x = x % 64;
    y = y % 32;

    if (x == 0) ++y;
}
