/********************************************
 ** This file is generated by AppGenerator **
 ********************************************/

#include "SimpleSwitch.gen.hpp"
#include "TLL.h"

#include <iostream>

SimpleSwitch::SimpleSwitch()
{
    std::cout << "Create SimpleSwitch instance." << std::endl;
}

SimpleSwitch::~SimpleSwitch()
{
    std::cout << "Delete SimpleSwitch instance." << std::endl;
}

void SimpleSwitch::init()
{

}

void SimpleSwitch::run()
{

}

void SimpleSwitch::terminate()
{

}

void SimpleSwitch::onTouched(tll::TouchInfo ti)
{

}

void SimpleSwitch::onMoved(tll::TouchInfo ti)
{

}

void SimpleSwitch::onReleased(tll::TouchInfo ti)
{
    std::system("bto_advanced_USBIR_cmd -d `cat switch_OnOff.txt`");
}
