/********************************************
 ** This file is generated by AppGenerator **
 ********************************************/

#include "Swipe.gen.hpp"
#include "TLL.h"

#include <iostream>

#define SWIPE_DISTANCE_THRESHOLD 4
#define SWIPE_VELOCITY_THRESHOLD 3

Swipe::Swipe()
    : is_swipe_valid(false)
    , ticks(0)
    , start_time(0)
{
    std::cout << "Create Swipe instance." << std::endl;
}

Swipe::~Swipe()
{
    std::cout << "Delete Swipe instance." << std::endl;
}

void Swipe::init()
{

}

void Swipe::run()
{
    this->ticks++;
}

void Swipe::terminate()
{

}

void Swipe::onTouched(tll::TouchInfo ti)
{
    if (ti.id != 0)
        return;

    this->is_swipe_valid = true;
    this->start_time = this->ticks;

    this->start_x = ti.x;
    this->start_y = ti.y;

    this->end_x = ti.x;
    this->end_y = ti.y;
}

void Swipe::onMoved(tll::TouchInfo ti)
{
    if (ti.id != 0)

    this->end_x = ti.x;
    this->end_y = ti.y;
}

void Swipe::onReleased(tll::TouchInfo ti)
{
    if (ti.id != 0)
        return;

    this->end_x = ti.x;
    this->end_y = ti.y;

    int32_t dx = this->end_x - this->start_x;
    int32_t dy = this->end_y - this->start_y;
    int32_t dist = std::sqrt(dx * dx + dy * dy);

    uint32_t elapsed = this->ticks - this->start_time;
    double velocity = dist / (elapsed + 1);

    if (dist >= SWIPE_DISTANCE_THRESHOLD && velocity >= SWIPE_VELOCITY_THRESHOLD)
    {
        if (std::abs(dx) > std::abs(dy))
        {
            // Horizontal swipe
            if (dx > 0)
            {
                // Right swipe
                std::cout << "Right swipe!" << std::endl;
            }
            else
            {
                // Left swipe
                std::cout << "Left swipe!" << std::endl;
            }
        }
        else
        {
            // Vertical swipe
            if (dy > 0)
            {
                // Down swipe
                std::cout << "Down swipe!" << std::endl;
            }
            else
            {
                // Up swipe
                std::cout << "Up swipe!" << std::endl;
            }
        }
    }
}
