/********************************************
 ** This file is generated by AppGenerator **
 ********************************************/

#include "TestApp.gen.hpp"
#include "TLL.h"

#include <iostream>

TestApp::TestApp()
{
    std::cout << "Create TestApp instance." << std::endl;
    tll::clear();
}

TestApp::~TestApp()
{
    std::cout << "Delete TestApp instance." << std::endl;
}

void TestApp::init()
{

}

void TestApp::run()
{

}

void TestApp::terminate()
{

}

void TestApp::onTouched(uint32_t x, uint32_t y)
{

}

void TestApp::onMoved(uint32_t x, uint32_t y)
{

}

void TestApp::onReleased()
{

}
