/********************************************
 ** This file is generated by AppGenerator **
 ********************************************/

#include "Theremin.gen.hpp"
#include "TLL.h"

#include <chrono>
#include <iostream>
#include <thread>

#define WIDTH  (64 - 1)
#define HEIGHT (32 - 1)

Theremin::Theremin()
    : is_touched(false)
    , x(0)
    , y(0)
{
    std::cout << "Create Theremin instance." << std::endl;
}

Theremin::~Theremin()
{
    std::cout << "Delete Theremin instance." << std::endl;
}

void Theremin::init()
{

}

void Theremin::run()
{
    this->is_running = true;

    while (tll::loop())
    {
        if (!this->is_running)
            return;

        tll::clear();

        // Volumeバーを表示
        tll::drawRect(0, 29, 64, 3, tll::Palette::color("Aqua"));

        // Pitchバーを表示
        tll::drawRect(0, 0, 3, 32, tll::Palette::color("Aqua"));

        // タッチされている場合タッチ点を表示
        if (this->is_touched)
        {
            tll::drawRect(this->x - 2, this->y - 2, 5, 5, tll::Palette::color("Red"));
        }
    }
}

void Theremin::terminate()
{
    this->is_running = false;
}

void Theremin::onTouched(uint32_t x, uint32_t y)
{
    this->x = x;
    this->y = y;
    this->is_touched = true;

    // タッチ座標によって音高をOSCメッセージにより送信
    float pitch = ((float)HEIGHT - this->y) / HEIGHT;
    tll::OscHandler::sendMessageWithFloat("/tll/app/Theremin/pitch", pitch);

    // タッチ座標によって音量をOSCメッセージにより送信
    float volume = ((float)WIDTH - this->x) / WIDTH;
    tll::OscHandler::sendMessageWithFloat("/tll/app/Theremin/volume", volume);
}

void Theremin::onMoved(uint32_t x, uint32_t y)
{
    this->x = x;
    this->y = y;

    // タッチ座標によって音高をOSCメッセージにより送信
    float pitch = ((float)HEIGHT - this->y) / HEIGHT;
    tll::OscHandler::sendMessageWithFloat("/tll/app/Theremin/pitch", pitch);

    // タッチ座標によって音量をOSCメッセージにより送信
    float volume = ((float)WIDTH - this->x) / WIDTH;
    tll::OscHandler::sendMessageWithFloat("/tll/app/Theremin/volume", volume);
}

void Theremin::onReleased()
{
    this->is_touched = false;
}
