/********************************************
 ** This file is generated by AppGenerator **
 ********************************************/

#include "Theremin.gen.hpp"
#include "TLL.h"

#include <chrono>
#include <iostream>
#include <thread>

#define WIDTH  (64 - 1)
#define HEIGHT (32 - 1)

Theremin::Theremin()
    : is_touched(false)
    , x(0)
    , y(0)
{
    std::cout << "Create Theremin instance." << std::endl;
}

Theremin::~Theremin()
{
    std::cout << "Delete Theremin instance." << std::endl;
}

void Theremin::init()
{
    tll::OscHandler::sendMessage("/tll/app/Theremin/init", "192.168.0.100", 3333);

    tll::OscHandler::sendMessageWithFloat("/tll/app/Theremin/volume", 0, "192.168.0.100", 3333);
    tll::OscHandler::sendMessageWithFloat("/tll/app/Theremin/pitch", 0, "192.168.0.100", 3333);
}

void Theremin::run()
{
    tll::clear();

    // Volumeバーを表示
    tll::drawRect(0, 29, 64, 3, tll::Palette::Aqua);

    // Pitchバーを表示
    tll::drawRect(0, 0, 3, 32, tll::Palette::Aqua);

    // タッチされている場合タッチ点を表示
    if (this->is_touched)
    {
        tll::drawRect(this->x - 2, this->y - 2, 5, 5, tll::Palette::Red);
    }
}

void Theremin::terminate()
{
    tll::OscHandler::sendMessage("/tll/app/Theremin/terminate", "192.168.0.100", 3333);
}

void Theremin::onTouched(tll::TouchInfo ti)
{
    if (ti.id == 0)
    {
        this->x = ti.x;
        this->y = ti.y;
        this->is_touched = true;

        // タッチ座標によって音高をOSCメッセージにより送信
        float pitch = ((float)HEIGHT - this->y) / HEIGHT;
        tll::OscHandler::sendMessageWithFloat("/tll/app/Theremin/pitch", pitch, "192.168.0.100", 3333);

        // タッチ座標によって音量をOSCメッセージにより送信
        float volume = (float)this->x / WIDTH;
        tll::OscHandler::sendMessageWithFloat("/tll/app/Theremin/volume", volume, "192.168.0.100", 3333);
    }
}

void Theremin::onMoved(tll::TouchInfo ti)
{
    if (ti.id == 0)
    {
        this->x = ti.x;
        this->y = ti.y;

        // タッチ座標によって音高をOSCメッセージにより送信
        float pitch = ((float)HEIGHT - this->y) / HEIGHT;
        tll::OscHandler::sendMessageWithFloat("/tll/app/Theremin/pitch", pitch, "192.168.0.100", 3333);

        // タッチ座標によって音量をOSCメッセージにより送信
        float volume = (float)this->x / WIDTH;
        tll::OscHandler::sendMessageWithFloat("/tll/app/Theremin/volume", volume, "192.168.0.100", 3333);
    }
}

void Theremin::onReleased(tll::TouchInfo ti)
{
    if (ti.id == 0)
    {
        this->is_touched = false;
        tll::OscHandler::sendMessageWithFloat("/tll/app/Theremin/volume", 0, "192.168.0.100", 3333);
        tll::OscHandler::sendMessageWithFloat("/tll/app/Theremin/pitch", 0, "192.168.0.100", 3333);
    }
}
