/********************************************
 ** This file is generated by AppGenerator **
 ********************************************/

#include "ToggleSwitch.gen.hpp"
#include "TLL.h"

#include <iostream>

ToggleSwitch::ToggleSwitch()
{
    std::cout << "Create ToggleSwitch instance." << std::endl;
}

ToggleSwitch::~ToggleSwitch()
{
    std::cout << "Delete ToggleSwitch instance." << std::endl;
}

void ToggleSwitch::init()
{

}

void ToggleSwitch::run()
{

}

void ToggleSwitch::terminate()
{

}

void ToggleSwitch::onTouched(tll::TouchInfo ti)
{

}

void ToggleSwitch::onMoved(tll::TouchInfo ti)
{

}

void ToggleSwitch::onReleased(tll::TouchInfo ti)
{

}
